version: '3.9'
services:
  webform:
    build: ./webform
    ports:
      - "8080:5000"
    env_file:
      - .env
    volumes:
      - ./db:/app/db

  n8n:
    build: ./n8n
    ports:
      - "5678:5678"
    environment:
      - DB_SQLITE_DATABASE=/root/n8n/database.sqlite
    volumes:
      - ./n8n:/root/n8n
